version: "3.9"

services:
  # Backend da aplicação
  backend:
    build: ./escola-backend
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: escola
      DB_DIALECT: postgres
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - postgres
    volumes:
      - ./escola-backend:/app
      - /app/node_modules
    networks:
      - escola-network
    command: >
      sh -c "npm install && \
             npx sequelize-cli db:create || true && \
             ([ -d '/app/migrations' ] && npx sequelize-cli db:migrate || echo 'Pulando migrações') && \
             npm run seed && \
             npm run dev"

  # Frontend da aplicação
  frontend:
    build: ./escola-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    volumes:
      - ./escola-frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - escola-network
    command: npm run dev

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escola
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - escola-network

volumes:
  postgres_data:

networks:
  escola-network:
    driver: bridge
